### ISSUE TITLE
Broken themes: albrecht-durer & kazimir-malevich

### ISSUE THREAD

**Issue by AviFS** [AviFS/apl-themes#4]
See issue #1. This looks to be an inheritance issue again.

For instance, it's set up to default to normal:
```css
.albrecht-durer .normal { background-color: rgba(255,255,255,1); }
```
But normal for albrecht-durer doesn't specify a text color, only background. It looks like there's then something else they should be inheriting/falling back on, but that's not implemented.

**Fix by taking care of issue #5 or by manually adding the css needed.**
